# Generated by Django 5.0.1 on 2025-05-22 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='signature',
            field=models.CharField(blank=True, help_text='Digital signature for certificate verification', max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['signature'], name='certificate_signatu_1fc0c7_idx'),
        ),
    ]
