# Generated by Django 5.0.1 on 2025-05-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_alter_certificate_status_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='course_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificate.course'),
        ),
    ]
